name: Test

on:
  # Trigger on pull request always (note the trailing colon)
  pull_request:

jobs:
  hi:
    name: Say hello

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -e {0}

    steps:
      - name: hi
        run: echo hi
